import { SourceDocument } from '../types';

// Mock content database for demonstration
const MOCK_CONTENT: Record<string, string> = {
  "https://www.petmd.com/cat/behavior/why-do-cats-purr": `
    Cats can purr when they are healthy and feeling good, but cats can also purr when they are sick or in pain. 
    By purring, the cat may be asking for care or comfort.
    One hypothesis is that the frequency of the purr, between 25 and 150 Hertz, can improve bone density and promote healing.
  `,
  "https://en.wikipedia.org/wiki/Purr": `
    The purr is a tonal buzzing sound made by some species of felids. 
    Domestic cats purr in a frequency range of 25 to 150 vibrations per second.
    Purring is often interpreted as a sign of contentment, though cats also purr when they are injured or in pain.
  `,
  "https://meowtel.com/blog/post/why-do-cats-purr-here-s-what-it-means": `
    Cats often purr when they are relaxed, comfortable, and content. This reaction is mostly involuntary.
    It happens when they are being petted, getting cuddles, or are just happy.
    However, cats may also purr when they are injured or unwell as a self-soothing mechanism.
  `,
  "https://www.vetradar.com/blog/why-do-cats-purr": `
    Cats purr for a variety of reasons, and it's not always a sign of contentment.
    While cats do purr when they're happy and relaxed, they also purr when they're in pain or distress.
    It functions as a communication tool and a healing mechanism.
  `,
  "https://www.reddit.com/r/explainlikeimfive/comments/1pnvg16/eli5_why_do_cats_purr_and_why_do_they_do_it_even/": `
    Cats in general purr when they're relaxed, but when they are feeling stressed they purr to calm themselves down. 
    The only two other times I've heard them purr is when they are hurt or giving birth.
    It's like how humans might hum or rock back and forth to soothe themselves.
  `,
  "https://www.cats.org.uk/cats-blog/why-does-my-cat-purr": `
    Why do cats purr? They're feeling happy and relaxed. 
    If your cat appears relaxed, with relaxed ears and whiskers, small pupils in their eyes, and their tail pointing up, they are likely happy.
    But pay attention to context.
  `,
  "https://cvets.net/reasons-why-cats-purr/": `
    Why Cats Purr – Stress. When stressed or anxious, cats will purr to calm their nerves and soothe themselves. 
    Because of the vibrations generated by the purr, it can help heal bones and tissues.
  `,
  "https://www.whiskas.co.uk/blog/behaviour/why-do-cats-purr": `
    Purring is a voluntary noise which cats choose to make, and they purr consciously to communicate how they're feeling.
    Kittens learn to purr when they are just a few days old to communicate with their mother.
  `,
  "https://www.scientificamerican.com/article/why-do-cats-purr/": `
    Because cats have adapted to conserve energy via long periods of rest and sleep, it is possible that purring is a low energy mechanism that stimulates muscles and bones without a lot of energy.
  `,
  "https://www.loc.gov/everyday-mysteries/zoology/item/why-and-how-do-cats-purr/": `
    As the kitten grows into adulthood, purring continues. Many suggest a cat purrs from contentment and pleasure. 
    But a cat also purrs when it is injured or in pain.
  `
};

export const fetchPageContent = async (url: string): Promise<string> => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 800));

  // Return mock content if available
  if (MOCK_CONTENT[url]) {
    return MOCK_CONTENT[url];
  }

  // Fallback for unknown URLs (simulating CORS or access error in this demo env)
  return `[Simulation: Unable to fetch real content from ${url} due to browser CORS restrictions. Using generic fallback text.]
  
  This is a fallback text simulating the content of the webpage. 
  In a real scenario, the extension would parse the DOM of the target page to extract paragraphs and headings.
  
  Hypothetically, if this page was about the search topic, it might contain relevant keywords about cats purring.
  `;
};